spring.application.name=bbs

# MySQLの設定
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/board}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPAの設定
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ログの設定
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ホットリロードを有効にするための設定
spring.devtools.restart.enabled=true

# Thymeleafログを有効にするための設定
spring.thymeleaf.cache=false
logging.level.org.thymeleaf=DEBUG


